
[00:00:53] [main/INFO]: Connecting to msb3.teamrapturemc.stream, 25565
[00:00:54] [Netty Client IO #7/INFO] [FML]: Server protocol version 2
[00:00:55] [Netty Client IO #7/INFO] [FML]: Attempting connection with missing mods [betterthanbunnies, betterthanllamas, controlling, ctgui, ctm, custombackgrounds, custommainmenu, defaultoptions, googlyeyes, itemzoom, modnametooltip, moreoverlays, mousetweaks, reauth, resourceloader, texfix, tipthescales, toastcontrol] at SERVER
[00:00:57] [Netty Client IO #7/INFO] [FML]: Injecting existing registry data into this client instance
[00:01:15] [Netty Client IO #7/INFO] [FML]: Applying holder lookups
[00:01:15] [Netty Client IO #7/INFO] [FML]: Holder lookups applied
[00:01:15] [Netty Client IO #7/INFO] [FML]: [Netty Client IO #7] Client side modded connection established
[00:01:15] [Netty Client IO #7/INFO] [mcjty.lib.varia.Logging]: DimensionSyncPacket: Registering: 
[00:01:15] [main/INFO] [mcjty.lib.varia.Logging]: Received dimension information from server
[00:01:15] [main/INFO] [Astral Sorcery]: [AstralSorcery] Using gateway screenshots for folder 'msb3.teamrapturemc.stream_66.70.181.158_25565'
[00:01:23] [main/INFO]: [CHAT] PaiAtiraNele has joined the network!
[00:01:23] [main/INFO]: [CHAT] Type /server <name> to join that server
[00:01:23] [Netty Client IO #7/WARN] [journeymap]: dim0 (Initialized) Bad configField entry during updateFrom(): enabled=null

[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [Netty Client IO #6/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: Foi forçado o cancelamento de uma conexão existente pelo host remoto
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_161]
	at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_161]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_161]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
[23:59:36] [main/INFO] [journeymap]: Mapping halted in C:\Users\Victor\Documents\Curse\Minecraft\Instances\Modern Skyblock 3 Departed (2)\journeymap\data\mp\Minecraft~Server\DIM0
[23:59:53] [main/INFO] [FML]: Applying holder lookups
[23:59:53] [main/INFO] [FML]: Holder lookups applied
[00:00:01] [main/INFO] [Mekanism]: VoiceServer: Stopping client connection...
[00:00:01] [main/ERROR] [Mekanism]: VoiceServer: Error while stopping client connection.
[00:00:01] [main/INFO] [STDERR]: [mekanism.client.voice.VoiceClient:disconnect:81]: java.lang.NullPointerException
[00:00:01] [main/INFO] [STDERR]: [mekanism.client.voice.VoiceClient:disconnect:81]: 	at mekanism.client.voice.VoiceClient.disconnect(VoiceClient.java:68)
[00:00:01] [main/INFO] [STDERR]: [mekanism.client.voice.VoiceClient:disconnect:81]: 	at mekanism.client.MekanismClient.reset(MekanismClient.java:51)
[00:00:01] [main/INFO] [STDERR]: [mekanism.client.voice.VoiceClient:disconnect:81]: 	at mekanism.client.ClientTickHandler.tickStart(ClientTickHandler.java:139)
[00:00:01] [main/INFO] [STDERR]: [mekanism.client.voice.VoiceClient:disconnect:81]: 	at mekanism.client.ClientTickHandler.onTick(ClientTickHandler.java:103)
[00:00:01] [main/INFO] [STDERR]: [mekanism.client.voice.VoiceClient:disconnect:81]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2485_ClientTickHandler_onTick_ClientTickEvent.invoke(.dynamic)
[00:00:01] [main/INFO] [STDERR]: [mekanism.client.voice.VoiceClient:disconnect:81]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[00:00:01] [main/INFO] [STDERR]: [mekanism.client.voice.VoiceClient:disconnect:81]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
[00:00:01] [main/INFO] [STDERR]: [mekanism.client.voice.VoiceClient:disconnect:81]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:343)
[00:00:01] [main/INFO] [STDERR]: [mekanism.client.voice.VoiceClient:disconnect:81]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1706)
[00:00:01] [main/INFO] [STDERR]: [mekanism.client.voice.VoiceClient:disconnect:81]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
[00:00:01] [main/INFO] [STDERR]: [mekanism.client.voice.VoiceClient:disconnect:81]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
[00:00:01] [main/INFO] [STDERR]: [mekanism.client.voice.VoiceClient:disconnect:81]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[00:00:01] [main/INFO] [STDERR]: [mekanism.client.voice.VoiceClient:disconnect:81]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:00:01] [main/INFO] [STDERR]: [mekanism.client.voice.VoiceClient:disconnect:81]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[00:00:01] [main/INFO] [STDERR]: [mekanism.client.voice.VoiceClient:disconnect:81]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[00:00:01] [main/INFO] [STDERR]: [mekanism.client.voice.VoiceClient:disconnect:81]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[00:00:01] [main/INFO] [STDERR]: [mekanism.client.voice.VoiceClient:disconnect:81]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[00:00:01] [main/INFO] [STDERR]: [mekanism.client.voice.VoiceClient:disconnect:81]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[00:00:01] [main/INFO] [Mekanism]: Reloaded config.
